server:
  port: 8091
  error:
    include-message: always

# http://localhost:8091/h2-console
spring:
  h2:
    console:
      enabled: true

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  datasource:
    initialization-mode: EMBEDDED
    url: jdbc:h2:mem:test_mem;MODE=PostgreSQL

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments:  false
        format_sql: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"



